Commit new Chart releases for TrueCharts
Signed-off-by: cyr-ius <cyr-ius@ipocus.net>

diff --git a/.github/workflows/charts-release.yaml b/.github/workflows/charts-release.yaml
--- a/.github/workflows/charts-release.yaml
+++ b/.github/workflows/charts-release.yaml
@@ -11,7 +11,6 @@ on:
       - "charts/**"
 
 jobs:
-
   release-scale:
     runs-on: ubuntu-latest
     outputs:
@@ -94,109 +93,108 @@ jobs:
           path: website
 
       #~ - name: Copy docs to website
-        #~ if: |
-          #~ steps.collect-changes.outputs.changesDetectedAfterTag == 'true'
-        #~ shell: bash
-        #~ run: |
-          #~ #!/bin/bash
-          #~ CHARTS=(${{ steps.collect-changes.outputs.modifiedChartsAfterTag }})
-          #~ echo "Removing Chart Docs prior to regeneration..."
-          #~ mkdir -p website/static/img/hotlink-ok/chart-icons || echo "chart-icons path already exists, continuing..."
-          #~ for i in "${CHARTS[@]}"
-          #~ do
-              #~ IFS='/' read -r -a chart_parts <<< "$i"
-              #~ if [ -f "charts/${chart_parts[0]}"/"${chart_parts[1]}/Chart.yaml" ]; then
-                #~ train=${chart_parts[0]}
-                #~ chart=${chart_parts[1]}
-                #~ echo "copying docs to website for ${chart}"
-                #~ mkdir -p website/docs/charts/${train}/${chart} || echo "chart path already exists, continuing..."
-                #~ mkdir -p tmp/website/docs/charts/${train}/${chart}/ || echo "chart path already exists, continuing..."
-                #~ if [[ -f "website/docs/charts/${train}/${chart}/CHANGELOG.md" ]]; then
-                   #~ echo "changelog found..."
-                   #~ true
-                #~ else
-                   #~ echo "changelog not found, starting with empty changelog..."
-                   #~ touch "website/docs/charts/${train}/${chart}/CHANGELOG.md"
-                #~ fi
-                #~ if [[ -f "website/docs/charts/${train}/${chart}/helm-security.md" ]]; then
-                   #~ echo "helm-security found..."
-                   #~ true
-                #~ else
-                   #~ echo "helm-security not found, starting with empty helm-security..."
-                   #~ touch "website/docs/charts/${train}/${chart}/helm-security.md"
-                   #~ echo "# Helm Security" >> website/docs/charts/${train}/${chart}/helm-security.md
-                #~ fi
-                #~ if [[ -f "website/docs/charts/${train}/${chart}/container-security.md" ]]; then
-                   #~ echo "container-security found..."
-                   #~ true
-                #~ else
-                   #~ echo "container-security not found, starting with empty container-security..."
-                   #~ touch "website/docs/charts/${train}/${chart}/container-security.md"
-                   #~ echo "# Helm Security" >> website/docs/charts/${train}/${chart}/container-security.md
-                #~ fi
-                #~ # keep some docs safe
-                #~ mv -f website/docs/charts/${train}/${chart}/CHANGELOG.md tmp/website/docs/charts/${train}/${chart}/CHANGELOG.md || :
-                #~ mv -f website/docs/charts/${train}/${chart}/helm-security.md tmp/website/docs/charts/${train}/${chart}/helm-security.md || :
-                #~ mv -f website/docs/charts/${train}/${chart}/container-security.md tmp/website/docs/charts/${train}/${chart}/container-security.md || :
+      #~ if: |
+      #~ steps.collect-changes.outputs.changesDetectedAfterTag == 'true'
+      #~ shell: bash
+      #~ run: |
+      #~ #!/bin/bash
+      #~ CHARTS=(${{ steps.collect-changes.outputs.modifiedChartsAfterTag }})
+      #~ echo "Removing Chart Docs prior to regeneration..."
+      #~ mkdir -p website/static/img/hotlink-ok/chart-icons || echo "chart-icons path already exists, continuing..."
+      #~ for i in "${CHARTS[@]}"
+      #~ do
+      #~ IFS='/' read -r -a chart_parts <<< "$i"
+      #~ if [ -f "charts/${chart_parts[0]}"/"${chart_parts[1]}/Chart.yaml" ]; then
+      #~ train=${chart_parts[0]}
+      #~ chart=${chart_parts[1]}
+      #~ echo "copying docs to website for ${chart}"
+      #~ mkdir -p website/docs/charts/${train}/${chart} || echo "chart path already exists, continuing..."
+      #~ mkdir -p tmp/website/docs/charts/${train}/${chart}/ || echo "chart path already exists, continuing..."
+      #~ if [[ -f "website/docs/charts/${train}/${chart}/CHANGELOG.md" ]]; then
+      #~ echo "changelog found..."
+      #~ true
+      #~ else
+      #~ echo "changelog not found, starting with empty changelog..."
+      #~ touch "website/docs/charts/${train}/${chart}/CHANGELOG.md"
+      #~ fi
+      #~ if [[ -f "website/docs/charts/${train}/${chart}/helm-security.md" ]]; then
+      #~ echo "helm-security found..."
+      #~ true
+      #~ else
+      #~ echo "helm-security not found, starting with empty helm-security..."
+      #~ touch "website/docs/charts/${train}/${chart}/helm-security.md"
+      #~ echo "# Helm Security" >> website/docs/charts/${train}/${chart}/helm-security.md
+      #~ fi
+      #~ if [[ -f "website/docs/charts/${train}/${chart}/container-security.md" ]]; then
+      #~ echo "container-security found..."
+      #~ true
+      #~ else
+      #~ echo "container-security not found, starting with empty container-security..."
+      #~ touch "website/docs/charts/${train}/${chart}/container-security.md"
+      #~ echo "# Helm Security" >> website/docs/charts/${train}/${chart}/container-security.md
+      #~ fi
+      #~ # keep some docs safe
+      #~ mv -f website/docs/charts/${train}/${chart}/CHANGELOG.md tmp/website/docs/charts/${train}/${chart}/CHANGELOG.md || :
+      #~ mv -f website/docs/charts/${train}/${chart}/helm-security.md tmp/website/docs/charts/${train}/${chart}/helm-security.md || :
+      #~ mv -f website/docs/charts/${train}/${chart}/container-security.md tmp/website/docs/charts/${train}/${chart}/container-security.md || :
 
-                #~ # remove old docs everywhere and recreate based on charts repo
-                #~ rm -rf website/docs/charts/*/${chart} || :
-                #~ mkdir -p website/docs/charts/${train}/${chart} || echo "chart path already exists, continuing..."
-                #~ yes | cp -rf charts/${train}/${chart}/docs/* website/docs/charts/${train}/${chart}/ 2>/dev/null || :
-                #~ yes | cp -rf charts/${train}/${chart}/icon.png website/static/img/hotlink-ok/chart-icons/${chart}.png 2>/dev/null || :
+      #~ # remove old docs everywhere and recreate based on charts repo
+      #~ rm -rf website/docs/charts/*/${chart} || :
+      #~ mkdir -p website/docs/charts/${train}/${chart} || echo "chart path already exists, continuing..."
+      #~ yes | cp -rf charts/${train}/${chart}/docs/* website/docs/charts/${train}/${chart}/ 2>/dev/null || :
+      #~ yes | cp -rf charts/${train}/${chart}/icon.png website/static/img/hotlink-ok/chart-icons/${chart}.png 2>/dev/null || :
 
-                #~ # Copy over kept documents
-                #~ mv -f tmp/website/docs/charts/${train}/${chart}/CHANGELOG.md website/docs/charts/${train}/${chart}/CHANGELOG.md 2>/dev/null || :
-                #~ mv -f tmp/website/docs/charts/${train}/${chart}/helm-security.md website/docs/charts/${train}/${chart}/helm-security.md 2>/dev/null || :
-                #~ mv -f tmp/website/docs/charts/${train}/${chart}/container-security.md website/docs/charts/${train}/${chart}/container-security.md 2>/dev/null || :
+      #~ # Copy over kept documents
+      #~ mv -f tmp/website/docs/charts/${train}/${chart}/CHANGELOG.md website/docs/charts/${train}/${chart}/CHANGELOG.md 2>/dev/null || :
+      #~ mv -f tmp/website/docs/charts/${train}/${chart}/helm-security.md website/docs/charts/${train}/${chart}/helm-security.md 2>/dev/null || :
+      #~ mv -f tmp/website/docs/charts/${train}/${chart}/container-security.md website/docs/charts/${train}/${chart}/container-security.md 2>/dev/null || :
 
-                #~ # Append SCALE changelog to actual changelog
-                #~ sed -i '1d' "website/docs/charts/${train}/${chart}/CHANGELOG.md" || echo "failed to sed 1d changelog..."
-                #~ cat "charts/${train}/${chart}/app-changelog.md" | cat - "website/docs/charts/${train}/${chart}/CHANGELOG.md" > temp && mv temp "website/docs/charts/${train}/${chart}/CHANGELOG.md"
-                #~ sed -i '1s/^/# Changelog\n\n/' "website/docs/charts/${train}/${chart}/CHANGELOG.md" || echo "failed to add changelog header..."
+      #~ # Append SCALE changelog to actual changelog
+      #~ sed -i '1d' "website/docs/charts/${train}/${chart}/CHANGELOG.md" || echo "failed to sed 1d changelog..."
+      #~ cat "charts/${train}/${chart}/app-changelog.md" | cat - "website/docs/charts/${train}/${chart}/CHANGELOG.md" > temp && mv temp "website/docs/charts/${train}/${chart}/CHANGELOG.md"
+      #~ sed -i '1s/^/# Changelog\n\n/' "website/docs/charts/${train}/${chart}/CHANGELOG.md" || echo "failed to add changelog header..."
 
-                #~ touch website/docs/charts/${train}/${chart}/index.md
-                #~ echo "# ${chart}" >> website/docs/charts/${train}/${chart}/index.md
-                #~ echo "" >> website/docs/charts/${train}/${chart}/index.md
-                #~ version=$(cat charts/${train}/${chart}/Chart.yaml | grep "^version: " | awk -F" " '{ print $2 }')
-                #~ appversion=$(cat charts/${train}/${chart}/Chart.yaml | grep "^appVersion: " | awk -F" " '{ print $2 }')
-                #~ echo '![Version: '"${version}"'](https://img.shields.io/badge/Version-'"${version}"'-informational?style=flat-square) ![Type: application](https://img.shields.io/badge/Type-application-informational?style=flat-square) ![AppVersion: '"${appversion}"'](https://img.shields.io/badge/AppVersion-'"${appversion}"'-informational?style=flat-square)' >> website/docs/charts/${train}/${chart}/index.md
-                #~ echo "" >> website/docs/charts/${train}/${chart}/index.md
-                #~ cat charts/${train}/${chart}/Chart.yaml | yq .description -r >> website/docs/charts/${train}/${chart}/index.md
-                #~ echo "" >> website/docs/charts/${train}/${chart}/index.md
-                #~ echo "## Available Documentation" >> website/docs/charts/${train}/${chart}/index.md
-                #~ echo "" >> website/docs/charts/${train}/${chart}/index.md
+      #~ touch website/docs/charts/${train}/${chart}/index.md
+      #~ echo "# ${chart}" >> website/docs/charts/${train}/${chart}/index.md
+      #~ echo "" >> website/docs/charts/${train}/${chart}/index.md
+      #~ version=$(cat charts/${train}/${chart}/Chart.yaml | grep "^version: " | awk -F" " '{ print $2 }')
+      #~ appversion=$(cat charts/${train}/${chart}/Chart.yaml | grep "^appVersion: " | awk -F" " '{ print $2 }')
+      #~ echo '![Version: '"${version}"'](https://img.shields.io/badge/Version-'"${version}"'-informational?style=flat-square) ![Type: application](https://img.shields.io/badge/Type-application-informational?style=flat-square) ![AppVersion: '"${appversion}"'](https://img.shields.io/badge/AppVersion-'"${appversion}"'-informational?style=flat-square)' >> website/docs/charts/${train}/${chart}/index.md
+      #~ echo "" >> website/docs/charts/${train}/${chart}/index.md
+      #~ cat charts/${train}/${chart}/Chart.yaml | yq .description -r >> website/docs/charts/${train}/${chart}/index.md
+      #~ echo "" >> website/docs/charts/${train}/${chart}/index.md
+      #~ echo "## Available Documentation" >> website/docs/charts/${train}/${chart}/index.md
+      #~ echo "" >> website/docs/charts/${train}/${chart}/index.md
 
-                #~ # Iterate over all files in the docs directory
-                #~ for file in website/docs/charts/${train}/${chart}/*.md; do
-                  #~ # Extract the file name and first line from each file
-                  #~ filename=$(basename "${file}")
-                  #~ title=$(head -n 1 "${file}" | sed 's/# //')
+      #~ # Iterate over all files in the docs directory
+      #~ for file in website/docs/charts/${train}/${chart}/*.md; do
+      #~ # Extract the file name and first line from each file
+      #~ filename=$(basename "${file}")
+      #~ title=$(head -n 1 "${file}" | sed 's/# //')
 
-                  #~ # Create a markdown link using the file name and title
-                  #~ link="[**${title}**](${filename%.md})"
-                  #~ if [ ${filename} != "index.md" ]; then
-                    #~ # Append the link to the index.md file
-                    #~ echo "- ${link}" >> website/docs/charts/${train}/${chart}/index.md
-                    #~ echo "" >> website/docs/charts/${train}/${chart}/index.md
-                  #~ fi
-                #~ done
+      #~ # Create a markdown link using the file name and title
+      #~ link="[**${title}**](${filename%.md})"
+      #~ if [ ${filename} != "index.md" ]; then
+      #~ # Append the link to the index.md file
+      #~ echo "- ${link}" >> website/docs/charts/${train}/${chart}/index.md
+      #~ echo "" >> website/docs/charts/${train}/${chart}/index.md
+      #~ fi
+      #~ done
 
-                #~ rm -rf temp || :
-              #~ fi
-          #~ done
+      #~ rm -rf temp || :
+      #~ fi
+      #~ done
 
       #~ - name: Commit Website Changes
-        #~ if: |
-          #~ steps.collect-changes.outputs.changesDetected == 'true'
-        #~ run: |
-          #~ cd website
-          #~ git config user.name "cyr-ius"
-          #~ git config user.email "cyr-ius@ipocus.net"
-          #~ git add --all
-          #~ git commit -sm "Commit released docs for TrueCharts" || exit 0
-          #~ git push
-
+      #~ if: |
+      #~ steps.collect-changes.outputs.changesDetected == 'true'
+      #~ run: |
+      #~ cd website
+      #~ git config user.name "cyr-ius"
+      #~ git config user.email "cyr-ius@ipocus.net"
+      #~ git add --all
+      #~ git commit -sm "Commit released docs for TrueCharts" || exit 0
+      #~ git push
 
       - name: Checkout Catalog
         uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
